### ISSUE TITLE
Cannot find libvlcjni.so

### ISSUE THREAD

**Issue by hsalazarl** [martijn00/VlcXamarin#13]
Hello, 

First of all, thank you for the project. I'm having an issue when running an app that I'm testing where it says that cannot find some libraries:

`08-08 04:06:18.552 W/VLC/LibVLC(10611): Unable to load the anw library: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/MyApp.MyApp-1/base.apk"],nativeLibraryDirectories=[/data/app/MyApp.MyApp-1/lib/x86, /vendor/lib, /system/lib]]] couldn't find "libanw.21.so"`

`08-08 04:06:18.552 E/VLC/LibVLC(10611): Can't load vlcjni library: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/MyApp.MyApp-1/base.apk"],nativeLibraryDirectories=[/data/app/MyApp.MyApp-1/lib/x86, /vendor/lib, /system/lib]]] couldn't find "libvlcjni.so"`

What do you think that can be happening? Any suggestions?

Thank you again.

**Comment by martijn00** [comment]
I think you are trying to run it in simulator or x86 device. This only supports ARM currently.
