### ISSUE TITLE
can this record phone camera?

### ISSUE THREAD

**Issue by hs79hs** [martijn00/VlcXamarin#15]
Great thanks. It works very well in my Xamarin project playing rtsp links of cameras.

I wonder whether it can access and record the phone camera itself. I'm doing a project which needs to record phone camera and generate HLS segments for live streaming. MediaRecorder cannot do that. So I turn to vlc. Any suggestions are welcome, thanks.

**Comment by martijn00** [comment]
No VLC can't record camera.

**Comment by hs79hs** [comment]
Ok, I turn to try ffmpeg and raw camera frames now, thanks again, great work.
