### ISSUE TITLE
Error in sample

### ISSUE THREAD

**Issue by martijn00** [martijn00/VlcXamarin#3]
Error message:

```
VlcXamarin\VlcXamarin.Sample\obj\Debug\android\src\mono\org\videolan\libvlc\VLCEvent_ListenerImplementor.java(31,31): 
Error:  error: package org.videolan.libvlc.VLCEvent does not exist
    org.videolan.libvlc.VLCEvent.Listener
```

Error appears in:

```
public class VLCEvent_ListenerImplementor
extends java.lang.Object
implements
    mono.android.IGCUserPeer,
    org.videolan.libvlc.VLCEvent.Listener
```

**Comment by martijn00** [comment]
@thefex Do you have idea's on this one? I've updated the main repo to the latest VLC library, but i get this error in the sample project when compiling. The binding project itself compiles fine.

**Comment by thefex** [comment]
I will take a look at this on Saturday/Sunday. Got similiar problems in past with other libraries.

**Comment by martijn00** [comment]
I got a bit further now when adding this:

```
<remove-node path="/api/package[@name='org.videolan.libvlc']/interface[@name='VLCEvent.Listener']" />
```

I run the app now, but then when it starts up i get this error:

```
   [Mono] Assembly Ref addref VlcXamarin.Sample[0xb4298640] -> mscorlib[0xb4298700]: 5
    [VLC] Unable to load the anw library: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.vlcxamarin.sample-1/base.apk"],nativeLibraryDirectories=[/data/app/com.vlcxamarin.sample-1/lib/x86, /vendor/lib, /system/lib]]] couldn't find "libanw.21.so"
    [VLC] Can't load vlcjni library: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.vlcxamarin.sample-1/base.apk"],nativeLibraryDirectories=[/data/app/com.vlcxamarin.sample-1/lib/x86, /vendor/lib, /system/lib]]] couldn't find "libvlcjni.so"
    [art] System.exit called, status: 1
```

EDIT:

Weird thing is that this happens in debug mode. When making a release build, the app runs, but i can't hear sound.

**Comment by martijn00** [comment]
Fixed it in my last commit now. The UnsatisfiedLinkError was because i was running this in simulator, but VLC doesn't have x86 libraries included.

The other thing was that i used a string as input for the stream, but a Android.Net.Uri was required.

**Comment by thefex** [comment]
you removed functionallity from orginal library, that's not valid fix in my opinion

**Comment by martijn00** [comment]
Hmm, might be, but i couldn't find any other workarounds. I would be happy if you could take a look at it!

**Comment by thefex** [comment]
Sure, I'll fix that. I had working weekend, I'll probably do it this Saturday.

**Comment by martijn00** [comment]
Thanks a lot! I've added you to the readme: https://github.com/martijn00/VlcXamarin#acknowledgements
