### ISSUE TITLE
SIGSEGV Error When Initialising LibVLCLibVLC Object

### ISSUE THREAD

**Issue by cbasah** [martijn00/VlcXamarin#4]
Hi,

Great job of having the Xamarin bindings for libvlc.

While I managed to get this to successfully run the sample project which plays the MP3 file, I am getting a SIGSEGV crash when I implemented it for video playing using TextureView which I have enabled hardware acceleration. Strangely enough, the crash occurs when the LibVLCLibVLC object is initialised.

/*************\* The Code **************/

_libVLC = new Org.Videolan.Libvlc.LibVLCLibVLC(); // error occurs here

_libVLC.SetOnHardwareAccelerationError(this);
_vv.KeepScreenOn = true;

// Create Media Player
_mediaPlayer = new Org.Videolan.Libvlc.MediaPlayer(_libVLC);

// Set up video output
Org.Videolan.Libvlc.IVLCVout vout = _mediaPlayer.VLCVout;
vout.SetVideoView(_vv);
vout.AttachViews();

Org.Videolan.Libvlc.MediaLibVLC m = new Org.Videolan.Libvlc.MediaLibVLC(_libVLC, this.selectedCamera.RemoteURLMobile);
_mediaPlayer.Media = m;
_mediaPlayer.Play();

/*************\* The Error **************/

The following is the error I am getting:

[mono-rt] Stacktrace:
[mono-rt]
[mono-rt]
[mono-rt] Attempting native Android stacktrace:
[mono-rt]
[mono-rt]   at ???+0 [0x0]
[mono-rt]
[mono-rt] =================================================================
[mono-rt] Got a SIGSEGV while executing native code. This usually indicates
[mono-rt] a fatal error in the mono runtime or one of the native libraries
[mono-rt] used by your application.
[mono-rt] =================================================================
[mono-rt]
[libc] Fatal signal 11 (SIGSEGV) at 0xe8e8ffe8 (code=-387383320), thread 1480 (wer_for_Android)

Any idea what's causing this? My emulator is using armbi-v7a. Target framework is JellyBean 4.1.

I have been pulling my hair for the past 2 days trying to fix this.

Regards,
Cris

**Comment by martijn00** [comment]
Can you check this again with the latest update?
